import { FaPrint, FaUser, FaCheckDouble, FaFileAlt } from 'react-icons/fa';
import { getStatusColor, getStatusIcon } from './utils.jsx';
import Modal from '../../Modal/Modal';

const ApplicationDetailsModal = ({
    application,
    onClose,
    renderActions
}) => {

    // Print Functionality
    const handlePrint = () => {
        if (!application) return;

        const printContent = `
            <div style="font-family: Arial, sans-serif; padding: 40px; color: #333;">
                <div style="text-align: center; margin-bottom: 40px; border-bottom: 2px solid #B91116; padding-bottom: 20px;">
                    <h1 style="color: #B91116; margin: 0;">LoanLink</h1>
                    <p style="margin: 5px 0; color: #666;">Application Details</p>
                </div>

                <table style="width: 100%; border-collapse: collapse; margin-bottom: 30px;">
                    <tr>
                        <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold; width: 30%;">Application ID:</td>
                        <td style="padding: 10px; border-bottom: 1px solid #eee;">${application.loanId || application._id || 'N/A'}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Applicant Name:</td>
                        <td style="padding: 10px; border-bottom: 1px solid #eee;">${application.userName}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Email:</td>
                        <td style="padding: 10px; border-bottom: 1px solid #eee;">${application.userEmail}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Category:</td>
                        <td style="padding: 10px; border-bottom: 1px solid #eee;">${application.category}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Requested Amount:</td>
                        <td style="padding: 10px; border-bottom: 1px solid #eee; font-size: 1.2em; color: #B91116;">৳${application.amount?.toLocaleString()}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Status:</td>
                        <td style="padding: 10px; border-bottom: 1px solid #eee; text-transform: capitalize;">${application.status || 'pending'}</td>
                    </tr>
                     <tr>
                        <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Fee Status:</td>
                        <td style="padding: 10px; border-bottom: 1px solid #eee; text-transform: capitalize;">${application.feeStatus || 'unpaid'}</td>
                    </tr>
                     <tr>
                        <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Date:</td>
                        <td style="padding: 10px; border-bottom: 1px solid #eee;">${new Date(application.createdAt).toLocaleDateString()}</td>
                    </tr>
                </table>

                 <div style="margin-top: 30px;">
                    <h3 style="border-bottom: 1px solid #ccc; padding-bottom: 10px;">Purpose</h3>
                    <p style="line-height: 1.6; background: #f9f9f9; padding: 15px; border-radius: 5px;">
                        ${application.purpose || 'No purpose specified.'}
                    </p>
                </div>

                <div style="margin-top: 50px; text-align: center; font-size: 0.8em; color: #999;">
                    <p>Generated by LoanLink System on ${new Date().toLocaleString()}</p>
                </div>
            </div>
        `;

        const printWindow = window.open('', '', 'width=800,height=600');
        printWindow.document.write('<html><head><title>Print Application</title></head><body>');
        printWindow.document.write(printContent);
        printWindow.document.write('</body></html>');
        printWindow.document.close();
        printWindow.focus();
        setTimeout(() => {
            printWindow.print();
            printWindow.close();
        }, 500);
    };

    return (
        <Modal
            isOpen={!!application}
            onClose={onClose}
            title={
                <div>
                    <h3 className="font-bold text-xl flex items-center gap-2">
                        <FaFileAlt /> Application Details
                    </h3>
                    {application && <p className="text-white/80 text-sm mt-1 font-normal opacity-80">ID: {application.loanId || application._id?.slice(-6).toUpperCase()}</p>}
                </div>
            }
        >
            {application && (
                <>
                    <div className="p-6 grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div className="space-y-4">
                            <div className="flex items-center gap-3 p-3 bg-base-200/50 rounded-xl">
                                <div className="avatar placeholder">
                                    <div className="bg-neutral text-neutral-content rounded-full w-10">
                                        <span>{application.userName?.charAt(0)}</span>
                                    </div>
                                </div>
                                <div>
                                    <p className="text-xs text-base-content/50 uppercase font-bold">Applicant</p>
                                    <p className="font-medium">{application.userName}</p>
                                    <p className="text-xs text-base-content/60">{application.userEmail}</p>
                                </div>
                            </div>

                            <div>
                                <p className="text-xs text-base-content/50 uppercase font-bold mb-1">Loan Category</p>
                                <p className="text-lg font-medium">{application.category}</p>
                            </div>

                            <div>
                                <p className="text-xs text-base-content/50 uppercase font-bold mb-1">Requested Amount</p>
                                <p className="text-2xl font-bold text-[#B91116]">৳{application.amount?.toLocaleString()}</p>
                            </div>
                        </div>

                        <div className="space-y-4">
                            <div>
                                <p className="text-xs text-base-content/50 uppercase font-bold mb-1">Current Status</p>
                                <div className={`badge gap-2 font-medium border-none py-3 px-4 ${getStatusColor(application.status, application.feeStatus)}`}>
                                    {getStatusIcon(application.status, application.feeStatus)}
                                    <span className="capitalize">{application.feeStatus === 'paid' ? 'Paid' : application.status}</span>
                                </div>
                            </div>

                            <div>
                                <p className="text-xs text-base-content/50 uppercase font-bold mb-1">Application Date</p>
                                <p className="font-medium">{new Date(application.createdAt).toLocaleDateString()}</p>
                            </div>

                            <div>
                                <p className="text-xs text-base-content/50 uppercase font-bold mb-1">Purpose</p>
                                <div className="bg-base-200/50 p-3 rounded-xl text-sm leading-relaxed min-h-[80px]">
                                    {application.purpose || "No purpose specified."}
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Modal Footer */}
                    <div className="p-4 bg-base-200/30 border-t border-base-200 flex justify-between gap-2 items-center">
                        <button
                            onClick={handlePrint}
                            className="btn btn-ghost btn-sm gap-2 text-base-content/70 hover:text-[#B91116]"
                        >
                            <FaPrint /> Print
                        </button>

                        <div className="flex gap-2">
                            {renderActions && renderActions(application)}
                            <button onClick={onClose} className="btn btn-ghost btn-sm hover:bg-base-200">Close</button>
                        </div>
                    </div>
                </>
            )}
        </Modal>
    );
};

export default ApplicationDetailsModal;
