import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FaTimes, FaFilePdf, FaTable } from 'react-icons/fa';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency } from '../../utils/loanUtils';

const AmortizationModal = ({ isOpen, onClose, schedule, loanDetails }) => {
    if (!isOpen) return null;

    const { amount, rate, years, emi, totalPayment, totalInterest } = loanDetails;

    // Generate PDF Function
    const handleDownloadPDF = () => {
        try {
            const doc = new jsPDF();

            // Header
            doc.setFontSize(20);
            doc.setTextColor(185, 17, 22); // Brand Red
            doc.text('LoanLink - Amortization Schedule', 14, 22);

            // Loan Details Section
            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            const currencyAmount = new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT' }).format(amount);
            const currencyEmi = new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT' }).format(emi);
            const currencyTotalInterest = new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT' }).format(totalInterest);
            const currencyTotalPayment = new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT' }).format(totalPayment);

            doc.text(`Loan Amount: ${currencyAmount}`, 14, 35);
            doc.text(`Interest Rate: ${rate}%`, 14, 42);
            doc.text(`Tenure: ${years} Years`, 14, 49);

            doc.text(`Monthly EMI: ${currencyEmi}`, 110, 35);
            doc.text(`Total Interest: ${currencyTotalInterest}`, 110, 42);
            doc.text(`Total Payment: ${currencyTotalPayment}`, 110, 49);

            // Table
            const tableColumn = ["Month", "EMI", "Principal", "Interest", "Balance"];
            const tableRows = [];

            schedule.forEach(row => {
                const rowData = [
                    row.month,
                    new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT' }).format(row.emi),
                    new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT' }).format(row.principalPayment),
                    new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT' }).format(row.interestPayment),
                    new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT' }).format(row.balance)
                ];
                tableRows.push(rowData);
            });

            // Use autoTable directly passing the doc instance
            autoTable(doc, {
                startY: 60,
                head: [tableColumn],
                body: tableRows,
                theme: 'grid',
                headStyles: { fillColor: [185, 17, 22] }, // Brand Red
                styles: { fontSize: 10, cellPadding: 2 },
                alternateRowStyles: { fillColor: [245, 245, 245] }
            });

            // Footer
            doc.setFontSize(10);
            doc.setTextColor(150, 150, 150);
            doc.text('Generated by LoanLink Loan Management System', 14, doc.internal.pageSize.height - 10);

            doc.save(`Loan_Schedule_${amount}_${years}yr.pdf`);
        } catch (error) {
            console.error("PDF generation failed:", error);
            // Fallback for debugging if import failed
            alert("PDF download failed. Please check console.");
        }
    };

    return (
        <AnimatePresence>
            <div className="fixed inset-0 z-[9999] flex items-center justify-end md:justify-center bg-black/50 backdrop-blur-sm p-0 md:p-4">
                <motion.div
                    initial={{ opacity: 0, y: '100%' }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: '100%' }}
                    transition={{ type: "spring", damping: 25, stiffness: 500 }}
                    className="bg-white w-full max-w-4xl h-[90vh] md:h-[85vh] rounded-t-2xl md:rounded-2xl shadow-2xl flex flex-col overflow-hidden"
                >
                    {/* Header */}
                    <div className="bg-[#B91116] p-4 flex justify-between items-center text-white shrink-0">
                        <div className="flex items-center gap-3">
                            <FaTable className="text-xl md:text-2xl" />
                            <h2 className="text-lg md:text-xl font-bold">Repayment Schedule</h2>
                        </div>
                        <button
                            onClick={onClose}
                            className="p-2 hover:bg-white/20 rounded-full transition-colors"
                        >
                            <FaTimes className="text-xl" />
                        </button>
                    </div>

                    {/* Summary Cards */}
                    <div className="shrink-0 p-4 bg-gray-50 border-b overflow-x-auto">
                        <div className="flex md:grid md:grid-cols-3 gap-3 min-w-max md:min-w-0">
                            <div className="bg-white p-3 md:p-4 rounded-xl shadow-sm border border-gray-100 min-w-[140px]">
                                <p className="text-xs md:text-sm text-gray-500">Loan Amount</p>
                                <p className="text-lg md:text-xl font-bold text-gray-800">{formatCurrency(amount)}</p>
                            </div>
                            <div className="bg-white p-3 md:p-4 rounded-xl shadow-sm border border-gray-100 min-w-[140px]">
                                <p className="text-xs md:text-sm text-gray-500">Total Interest</p>
                                <p className="text-lg md:text-xl font-bold text-[#B91116]">{formatCurrency(totalInterest)}</p>
                            </div>
                            <div className="bg-white p-3 md:p-4 rounded-xl shadow-sm border border-gray-100 min-w-[140px]">
                                <p className="text-xs md:text-sm text-gray-500">Monthly EMI</p>
                                <p className="text-lg md:text-xl font-bold text-gray-800">{formatCurrency(emi)}</p>
                            </div>
                        </div>
                    </div>

                    {/* Scrollable Table Area */}
                    <div
                        className="flex-1 overflow-y-auto overflow-x-auto bg-white p-0 min-h-0"
                        data-lenis-prevent="true"
                    >
                        <table className="table table-xs md:table-md w-full min-w-[600px] md:min-w-full">
                            <thead>
                                <tr className="bg-base-200 text-base-content sticky top-0 z-10 shadow-sm">
                                    <th className="font-bold">Month</th>
                                    <th className="font-bold">EMI</th>
                                    <th className="font-bold">Principal</th>
                                    <th className="font-bold">Interest</th>
                                    <th className="font-bold">Balance</th>
                                </tr>
                            </thead>
                            <tbody>
                                {schedule.map((row) => (
                                    <tr key={row.month} className="hover border-b border-base-100">
                                        <td className="font-bold text-center">{row.month}</td>
                                        <td>{formatCurrency(row.emi)}</td>
                                        <td className="text-green-600 font-medium">+{formatCurrency(row.principalPayment)}</td>
                                        <td className="text-red-500 font-medium">-{formatCurrency(row.interestPayment)}</td>
                                        <td className="font-bold">{formatCurrency(row.balance)}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>

                    {/* Footer Actions */}
                    <div className="p-4 border-t bg-white shrink-0 flex flex-col-reverse md:flex-row justify-end gap-3 z-20 shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.05)]">
                        <button
                            onClick={onClose}
                            className="btn btn-ghost w-full md:w-auto"
                        >
                            Close
                        </button>
                        <button
                            onClick={handleDownloadPDF}
                            className="btn bg-[#B91116] hover:bg-[#900d11] text-white border-none gap-2 px-6 w-full md:w-auto"
                        >
                            <FaFilePdf /> <span className="hidden md:inline">Download Schedule PDF</span><span className="md:hidden">Download PDF</span>
                        </button>
                    </div>
                </motion.div>
            </div>
        </AnimatePresence>
    );
};

export default AmortizationModal;
